---
label: Products
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Nom
- name: tags
  type: tag_list
  default:
  - product
  label: Tags
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: price
  type: number
  label: Prix
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: conditions
  type: text
  config:
    required: false
  label: Conditions
  description: Par exemple <strong>Enfant. délai 2-3 sem.</strong>
- name: reviews
  type: field_group_list
  fields:
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: text
  config:
    min: 
    max: 
    labelField: 
  label: Avis
pages:
- products/bavoir-luke.md
- products/bouillottes-josephine.md
- products/calendrier-de-l-avent-a-garnir.md
- products/chaussettes-rudolf.md
- products/chouchou-camille.md
- products/collier-cervical-chauffant.md
- products/echarpe-marthe.md
- products/echarpe-phillipa.md
- products/echarpe-stan.md
- products/etui-a-brosse-a-dents-horace.md
- products/etui-a-lunettes-marvin.md
- products/etui-pour-tablette-joshua.md
- products/kit-naissance-personnalise.md
- products/kit-week-end-a-borneo.md
- products/masque-barriere-jeune-enfant-2-4-ans.md
- products/masque-barriere-junior-5-12-ans.md
- products/masque-barriere-selection-teenagers.md
- products/masque-barriere-taille-adulte.md
- products/masque-de-nuit-bobby.md
- products/pochette-nomade.md
- products/protege-carnet-de-sante-personnalise.md
- products/robe-celestine-ete.md
- products/robe-celestine-hiver.md
- products/sac-a-bonbons-tabatha.md
- products/sac-a-doudou-personnalise.md
- products/sac-a-linge-marcus.md
- products/sac-a-tartes-octave.md
- products/set-de-table-corentin.md
- products/snood-achille.md
- products/snood-colette.md
- products/snood-edward.md
- products/snood-hadryen.md
- products/snood-octave.md
- products/tablier-aymeric.md
- products/trousse-paloma-grand-format.md
- products/trousse-paloma.md
- products/valise-d-artiste-leonard.md
