---
label: Products
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Nom
- name: tags
  type: tag_list
  default:
  - product
  label: Tags
- name: images
  type: image_gallery
  config: {}
  label: Images
pages:
- products/snood-achille.md
- products/snood-octave.md
