---
label: Products
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Nom
- name: tags
  type: tag_list
  default:
  - product
  label: Tags
- name: images
  type: image_gallery
  config: {}
  label: Images
pages:
- products/bavoir-luke.md
- products/bouillottes-josephine.md
- products/collier-cervical-chauffant.md
- products/echarpe-marthe.md
- products/echarpe-phillipa.md
- products/echarpe-stan.md
- products/kit-naissance-personnalise.md
- products/robe-celestine-ete.md
- products/robe-celestine-hiver.md
- products/sac-a-tartes-octave.md
- products/snood-achille.md
- products/snood-colette.md
- products/snood-hadryen.md
- products/snood-octave.md
- products/tablier-aymeric.md
